// <auto-generated />
using System;
using CodeD.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeD.Infrastructure.Migrations
{
    [DbContext(typeof(CodeDDbContext))]
    [Migration("20250402103106_AddClusterColumns")]
    partial class AddClusterColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("CodeD")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeD.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<long>("RowId"), 1L, null, null, null, null, null);

                    b.Property<uint?>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("RowId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Category_RowId");

                    b.ToTable("Category", "CodeD");
                });

            modelBuilder.Entity("CodeD.Domain.Posts.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("PostStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RowId"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<long>("RowId"), 1L, null, null, null, null, null);

                    b.Property<uint?>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("RowId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Post_RowId");

                    b.ToTable("Post", "CodeD");
                });

            modelBuilder.Entity("CodeD.Domain.Categories.Category", b =>
                {
                    b.OwnsOne("CodeD.Domain.Abstractions.ExternalReference", "ExternalReference", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ItemId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("SourceItemId");

                            b1.Property<string>("ProviderKey")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("SourceProviderKey");

                            b1.Property<string>("Version")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("SourceVersion");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Category", "CodeD");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.OwnsOne("CodeD.Domain.Abstractions.WhoColumns", "WhoColumns", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAt");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTimeOffset>("ModifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ModifiedAt");

                            b1.Property<Guid>("ModifiedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("ModifiedBy");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Category", "CodeD");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.Navigation("ExternalReference")
                        .IsRequired();

                    b.Navigation("WhoColumns")
                        .IsRequired();
                });

            modelBuilder.Entity("CodeD.Domain.Posts.Post", b =>
                {
                    b.HasOne("CodeD.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CodeD.Domain.Abstractions.ExternalReference", "ExternalReference", b1 =>
                        {
                            b1.Property<Guid>("PostId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ItemId")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("SourceItemId");

                            b1.Property<string>("ProviderKey")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("SourceProviderKey");

                            b1.Property<string>("Version")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("SourceVersion");

                            b1.HasKey("PostId");

                            b1.ToTable("Post", "CodeD");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.OwnsOne("CodeD.Domain.Abstractions.WhoColumns", "WhoColumns", b1 =>
                        {
                            b1.Property<Guid>("PostId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("CreatedAt");

                            b1.Property<Guid>("CreatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("CreatedBy");

                            b1.Property<DateTimeOffset>("ModifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ModifiedAt");

                            b1.Property<Guid>("ModifiedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("ModifiedBy");

                            b1.HasKey("PostId");

                            b1.ToTable("Post", "CodeD");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.Navigation("ExternalReference")
                        .IsRequired();

                    b.Navigation("WhoColumns")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
